# Generated by Django 4.1 on 2025-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BitkiAI",
            "0003_alter_workflowstep_classes_alter_workflowstep_result_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pesticide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="İlaç Adı")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pesticides/",
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "weight_gram",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Ağırlık (g)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fiyat (₺)"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Stok Adedi"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Yayında"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bitki İlacı",
                "verbose_name_plural": "Bitki İlaçları",
                "ordering": ["-created_at"],
            },
        ),
    ]
