# Generated by Django 5.0.8 on 2025-07-10 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitkiAI", "0004_pesticide"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowstep",
            options={"ordering": ["workflow", "order"]},
        ),
        migrations.AddField(
            model_name="workflow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
