# Generated by Django 5.0.8 on 2025-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitkiAI", "0006_workflow_classes_workflow_image_workflow_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticide",
            name="sales_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Satış Adedi"),
        ),
    ]
