# Generated by Django 5.0.8 on 2025-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitkiAI", "0007_pesticide_sales_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticide",
            name="disease",
            field=models.CharField(
                default="", max_length=200, verbose_name="Hastalık Adı"
            ),
            preserve_default=False,
        ),
    ]
