# Generated by Django 5.0.8 on 2025-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitkiAI", "0008_pesticide_disease"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticide",
            name="class_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Sınıf Kodu"
            ),
            preserve_default=False,
        ),
    ]
