# Generated by Django 5.0.8 on 2025-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BitkiAI", "0009_pesticide_class_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Sınıf Kodu"
                    ),
                ),
                (
                    "disease",
                    models.CharField(max_length=200, verbose_name="Hastalık Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hastalık Bilgisi",
                "verbose_name_plural": "Hastalık Bilgileri",
                "ordering": ["disease"],
            },
        ),
    ]
